---
execute:
  freeze: auto
---

# Help {#help}

Working with `targets` can be challenging, and sometimes you may need help from a human.
However, offering that help can be just as challenging because every use case is different.
If you make your questions easy to answer, you will get faster, more useful responses.
This chapter shares advice about asking effective questions.
Please read this page in full before reaching out for support.

:::{.callout-note}

## Summary

Before you post a question, please read through all the sections of in this chapter.

* Follow the [code of conduct](https://ropensci.org/code-of-conduct/).
* Do not post sensitive or confidential information.
* Search existing posts.
* Update your R packages.
* Isolate the source of the error.
* Write a reprex.
:::

## Before you post

### Code of conduct

All developers, users, and other discussants must follow the [code of conduct](https://ropensci.org/code-of-conduct/). Please read it before engaging in discussion.

### Sensitive information

The discussion forums from @sec-contact are open to the public, and anyone with an internet connection can read them. Please do not share any company confidential information, personally identifiable information, private research data, or any other sensitive information.

### Search existing posts

It is tedious to answer the same question repeatedly, so please check if your question already has an answer.
@sec-contact links to searchable online discussion forums with thousands of existing posts.
If a relevant thread already exists, please read it first.
Then, if necessary, please comment there instead of starting a new post.

### Try troubleshooting

For specific errors or other issues, please read this chapter's section on troubleshooting. Please try to work through the steps yourself before posting a question.

## Troubleshooting

If you are struggling with `targets`, please follow the steps below first.
Even if you do not solve the problem on your own, your findings from troubleshooting will help you ask effective questions when you talk to a live human.

### Update your R packages

If you encounter a bug in `targets` or `tarchetypes`, the bug may have already been fixed in a newer version. Before posting, please try again with the latest CRAN release of `targets` (or `tarchetypes`), then again with the GitHub development version if needed. Please see <https://docs.ropensci.org/targets/#installation> for installation instructions.

### Isolate the source of the error

An error in a `targets` pipeline might not originate from the `targets` package itself.
The underlying cause might be a bug in [one of the R packages that `targets` depends on](https://github.com/ropensci/targets/blob/a419fb99d3c07e2270f2507c8d6ec83d87cb85d6/DESCRIPTION#L58-L112), or it might come from the custom R code you inject into your pipeline.
As best you can, please try to find the true source of the error.
For example, try running similar code without the `targets` package and see if you get the same error.
If the error does not come from `targets` itself, please do not post your question on a `targets`-focused discussion forum.

### Write a reprex

When something goes wrong, it is natural to simply share the error and ask why it happened.
But this is not enough information, not even for an expert in `targets`.
Any response would be guesswork, and guesses about computer code are usually wrong.
The person helping you needs to actually run your code.
This is the only way to test that a solution really works.

When you ask for help with a problem, please provide a reprex^[Also known as a reproducible example, minimal reproducible example, or minimal working example.].
A reprex is a small sample of runnable code that emulates the problem.
If you provide a reprex, the person helping you can troubleshoot empirically, and the responses you get will be faster and more useful.

A viable reprex must:

1. Be runnable by anyone else. For example, do not reference private files that only you can access.
2. Actually generate the expected error when someone else runs it.

In addition, a good reprex:

* Has [clean and readable](https://style.tidyverse.org/) code.
* Runs quickly on any machine.
* Is simple and concise enough for someone else to digest quickly and understand without much effort.

The following posts explain how to write a good reprex.

  * <https://stackoverflow.com/help/minimal-reproducible-example>
  * <https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example>
  * <https://reprex.tidyverse.org/>
  * <https://www.tidyverse.org/blog/2017/12/workflow-vs-script/>

The discussion forums of `targets` and `tarchetypes` have excellent reprexes from users.

  * <https://github.com/ropensci/tarchetypes/discussions/90>
  * <https://github.com/ropensci/tarchetypes/discussions/102>
  * <https://github.com/ropensci/tarchetypes/discussions/126>
  * <https://github.com/ropensci/tarchetypes/discussions/129>
  * <https://github.com/ropensci/targets/discussions/884>
  * <https://github.com/ropensci/targets/discussions/953#discussioncomment-3842883>
  * <https://github.com/ropensci/targets/discussions/944>
  * <https://github.com/ropensci/targets/discussions/945>
  * <https://github.com/ropensci/targets/discussions/954>

## Contact {#sec-contact}

There are many ways to reach out.

### Community

You can reach out to the R community at these public forums.

* [Stack Overflow](https://stackoverflow.com/)
* [Posit Community](https://community.rstudio.com/)
* [rOpenSci Discuss](https://discuss.ropensci.org)
* [Mastodon](https://mastodon.social) (`#rstats` hashtag)
* [R subreddit](https://www.reddit.com/r/rstats/)

### Maintainer

To contact the maintainer directly, please post to the relevant public [GitHub Discussions](https://github.com/features/discussions) page of the package (if your question does not already exist).^[You may need to create a free [GitHub](https://github.com/) account, but the process is straightforward.] Examples:

* `targets`: <https://github.com/ropensci/targets/discussions>
* `tarchetypes`: <https://github.com/ropensci/tarchetypes/discussions>
* `gittargets`: <https://github.com/ropensci/gittargets/discussions>
* `jagstargets`: <https://github.com/ropensci/jagstargets/discussions>
* `stantargets`: <https://github.com/ropensci/stantargets/discussions>

Public discussions are searchable, and they help answer questions from other users in the future.
So please avoid private emails, instant messages, or mentions on social media.

## How you can help {#sec-help-user}

If you have a free moment to help someone else in the discussion and issue forums, we would greatly appreciate it. Any amount of engagement, no matter how small, makes a tremendous difference. C.f. <https://ropensci.org/blog/2024/02/29/targets-call-help/>.
